#!/usr/bin/env node
'use strict';
process.title = 'cost';
var fs = require('fs');
var path = require('path');
var Promise = require('bluebird');
var clc = require('cli-color');
var prettyBytes = require('pretty-bytes');
var cost = require('../lib/cost');

var options = require('nopt')(
{	'help': Boolean,
	'bytes': Boolean,
	'simple': Boolean
}, {
	'?': '--help',
	'b': '--bytes',
	's': '--simple'
});
var paths = options.argv.remain;

if (options.help || !paths.length) {
	console.log('' + fs.readFileSync(path.join(__dirname, 'help.txt')));
} else {
	Promise.each(paths.map(prepareCostResult), function (data) {
		if (paths.length > 1) {
			var style = clc.underline[data.isError ? 'red' : 'green'];
			console.log(style(data.path) + '\n' + data.value);
		} else {
			console.log(data.value);
		}
	});
}

function prepareCostResult(path) {
	return cost(path)
		.then(function (data) {
				if (!options.bytes) {data.value = prettyBytes(data.value);}
				if (!options.simple) {
					var details = [];
					if (data.minify) {details.push('minified');}
					if (data.gzip) {details.push('gzipped');}
					if (details.length) {
						data.value += ' (' + details.join(', ') + ')';
					}
				}
				return data;
			}, function (err) {
				return {
					path: path,
					value: 'ERROR: ' + (err.statusCode ? err.statusCode + ' ' : '') + err.message,
					isError: true
				};
			});
}
